/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.QuanLyThuVien;
import Model.BanDoc;
import Model.ChiTietMuon;
import Model.MuonTra;
import Model.NhanVien;
import Model.Sach;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Linh
 */
public class frmLuotMuonMoi extends javax.swing.JFrame {

    /**
     * Creates new form frmLuotMuonMoi
     */
    private BanDoc banDoc = null;
    private NhanVien nhanVien = null;
    private QuanLyThuVien quanLyThuVien = new QuanLyThuVien();
    private frmMain main = null;
    private int soTienCoc = 0;

    public frmLuotMuonMoi(BanDoc banDoc, NhanVien nhanVien, frmMain main) {
        this.banDoc = banDoc;
        this.nhanVien = nhanVien;
        this.main = main;
        initComponents();
    }

    public frmLuotMuonMoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSachDuocChon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSoMuon = new javax.swing.JTextField();
        txtBanDoc = new javax.swing.JTextField();
        txtMaSoBanDoc = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtMaSoNhanVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        dcsHanTra = new com.toedter.calendar.JDateChooser();
        txtSoTienCoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnLuuLM = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiemSach = new javax.swing.JTextField();
        cbxTimKiemSach = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lượt mượn mới");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin mượn"));

        tblSachDuocChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số sách", "Tên sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSachDuocChon);
        if (tblSachDuocChon.getColumnModel().getColumnCount() > 0) {
            tblSachDuocChon.getColumnModel().getColumn(0).setResizable(false);
            tblSachDuocChon.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblSachDuocChon.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel4.setText("Mã số mượn");

        jLabel5.setText("Bạn đọc");

        jLabel6.setText("Mã số bạn đọc");

        jLabel7.setText("Ngày mượn");

        jLabel8.setText("Hạn trả");

        jLabel10.setText("Mã số nhân viên");

        txtMaSoMuon.setEditable(false);

        txtBanDoc.setEditable(false);

        txtMaSoBanDoc.setEditable(false);

        txtNgayMuon.setEditable(false);

        txtMaSoNhanVien.setEditable(false);

        jLabel1.setText("Năm sinh");

        txtNgaySinh.setEditable(false);

        dcsHanTra.setDateFormatString("yyyy-MM-dd");

        txtSoTienCoc.setEditable(false);

        jLabel3.setText("Số tiền cọc");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayMuon)
                                    .addComponent(txtMaSoNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(dcsHanTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaSoMuon)
                                    .addComponent(txtBanDoc)
                                    .addComponent(txtMaSoBanDoc)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(138, 138, 138))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaSoBanDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(dcsHanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Go.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/action_export.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnLuuLM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnLuuLM.setText("Lưu lại");
        btnLuuLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.gif"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sách"));

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSach);

        jLabel2.setText("Tìm kiếm");

        txtTimKiemSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSachKeyReleased(evt);
            }
        });

        cbxTimKiemSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã số sách", "Tên sách", "Nhà xuất bản", "Tác giả", "Thể loại" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuLM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDong)
                        .addGap(29, 29, 29))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLuuLM)
                            .addComponent(btnDong))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLuuLM, btnDong});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        hienThiSach("select * from sach");
        Date date = new Date();
        txtMaSoMuon.setText("MT" + (date.getTime() / 1000));
        txtMaSoBanDoc.setText(banDoc.getMaSo());
        txtMaSoNhanVien.setText(nhanVien.getMaSo());
        txtBanDoc.setText(banDoc.getHoTen());
        txtNgayMuon.setText(quanLyThuVien.dateToString(date));
        txtNgaySinh.setText(banDoc.getNamSinh() + "");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numRowSelected = tblSach.getSelectedRow();
        if (numRowSelected < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sách nào !", "Cảnh báo", 2);
            return;
        }
        if (!check()) {
            JOptionPane.showMessageDialog(null, "Sách đã được chọn!", "Cảnh báo", 2);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblSachDuocChon.getModel();
        Object[] objRow = new Object[2];
        objRow[0] = tblSach.getValueAt(numRowSelected, 0);
        objRow[1] = tblSach.getValueAt(numRowSelected, 1);

        model.addRow(objRow);
        tinhTienCoc();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimKiemSachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSachKeyReleased
        String sql = "";
        String kieuTimKiemSach = "";
        switch (cbxTimKiemSach.getSelectedItem().toString()) {
            case "Mã số sách":
                kieuTimKiemSach = "MaSoSach";
                break;
            case "Tên sách":
                kieuTimKiemSach = "TenSach";
                break;
            case "Nhà xuất bản":
                kieuTimKiemSach = "NhaXuatBan";
                break;
            case "Thể loại":
                kieuTimKiemSach = "TheLoai";
                break;
            case "Tác giả":
                kieuTimKiemSach = "TacGia";
                break;
        }
        sql = "select * from sach where " + kieuTimKiemSach + " like '%"
                + txtTimKiemSach.getText() + "%';";
        hienThiSach(sql);
    }//GEN-LAST:event_txtTimKiemSachKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numRowSelected = tblSachDuocChon.getSelectedRow();
        if (numRowSelected < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sách nào !", "Cảnh báo", 2);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblSachDuocChon.getModel();
        model.removeRow(numRowSelected);
        tinhTienCoc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String path = "";
        if (tblSachDuocChon.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sách nào !");
            return;
        }
        java.sql.Date ngayMuon = quanLyThuVien.dateToDate(new Date());
        java.sql.Date hanTra = new java.sql.Date(dcsHanTra.getDate().getTime());
        java.sql.Date ngayTra = null;
        if (hanTra == null) {
            JOptionPane.showMessageDialog(null, "Hạn trả không chính xác !");
            return;
        }
        MuonTra muonTra = new MuonTra(txtMaSoMuon.getText(), txtMaSoBanDoc.getText(),
                ngayMuon, hanTra, ngayTra, txtMaSoNhanVien.getText(), 0, soTienCoc);

        if (quanLyThuVien.addMuonTra(muonTra)) {
            for (int i = 0; i < tblSachDuocChon.getRowCount(); i++) {
                ChiTietMuon chiTietMuon = new ChiTietMuon(txtMaSoMuon.getText(),
                        tblSachDuocChon.getValueAt(i, 0).toString(), "Đang mượn");
                if (!quanLyThuVien.addChiTietMuon(chiTietMuon)) {
                    JOptionPane.showMessageDialog(null, "Thêm sách " + tblSachDuocChon.getValueAt(i, 0).toString()
                            + " không thành công !");
                }
            }
            JFileChooser fcs = new JFileChooser();
            if (fcs.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                path = fcs.getSelectedFile().getAbsolutePath();
                if (quanLyThuVien.inPhieuMuon(banDoc, muonTra, nhanVien, tblSachDuocChon, path)) {
                    JOptionPane.showMessageDialog(null, "In phiếu thành công !");
                    main.hienThiMuonTra("select * from muontra where TrangThai = 1");
                    try {
                        Desktop.getDesktop().open(new File(path + ".pdf"));
                    } catch (IOException ex) {
                        Logger.getLogger(frmLuotMuonMoi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "In phiếu không thành công !");
                }

            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int isAccept = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?");
        if (isAccept == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private boolean check() {
        int numRowSelected = tblSach.getSelectedRow();
        for (int i = 0; i < tblSachDuocChon.getRowCount(); i++) {
            if (tblSachDuocChon.getValueAt(i, 0).equals(tblSach.getValueAt(numRowSelected, 0))) {
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLuotMuonMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLuotMuonMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLuotMuonMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLuotMuonMoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLuotMuonMoi().setVisible(true);
            }
        });
    }

    public void hienThiSach(String sql) {
        String[] colSach = {"Mã số", "Tên sách", "Tác giả", "Nhà Xuất bản",
            "Năm xuất bản", "Thể loại", "Giá"};
        DefaultTableModel model = new DefaultTableModel(colSach, 0);
        Object[] objSach = new Object[7];
        ArrayList<Sach> lstSach = new ArrayList<Sach>();
        lstSach = quanLyThuVien.getSach(sql);
        if (lstSach == null || lstSach.size() == 0) {
            return;
        }
        for (int i = 0; i < lstSach.size(); i++) {
            objSach[0] = lstSach.get(i).getMaSoSach();
            objSach[1] = lstSach.get(i).getTenSach();
            objSach[3] = lstSach.get(i).getNhaXuatBan();
            objSach[2] = lstSach.get(i).getTacGia();
            objSach[4] = lstSach.get(i).getNamXuatBan();
            objSach[5] = lstSach.get(i).getTheLoai();
            objSach[6] = lstSach.get(i).getGiaSach();
            model.addRow(objSach);
        }
        tblSach.setModel(model);
    }

    private void tinhTienCoc() {
        soTienCoc = 0;
        for (int i = 0; i < tblSach.getRowCount(); i++) {
            for (int j = 0; j < tblSachDuocChon.getRowCount(); j++) {
                if (tblSach.getValueAt(i, 0).toString().equals(tblSachDuocChon.getValueAt(j, 0))) {
                    soTienCoc += (int) tblSach.getValueAt(i, 6);
                }
            }
        }
        txtSoTienCoc.setText(soTienCoc + "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTimKiemSach;
    private com.toedter.calendar.JDateChooser dcsHanTra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton btnLuuLM;
    private javax.swing.JButton btnDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblSachDuocChon;
    private javax.swing.JTextField txtBanDoc;
    private javax.swing.JTextField txtMaSoBanDoc;
    private javax.swing.JTextField txtMaSoMuon;
    private javax.swing.JTextField txtMaSoNhanVien;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoTienCoc;
    private javax.swing.JTextField txtTimKiemSach;
    // End of variables declaration//GEN-END:variables
}
